### ISSUE TITLE
请问为什么需要Local.js才能使用？

### ISSUE THREAD

**Issue by HuanMeng0** [VincentChanX/shadowsocks-over-websocket#1]

**Comment by VincentChanX** [comment]
shadowsocks的基本工作流程：client <--[socks5]--> local.js <--[encrypted]--> server.js <---> target

local.js一般运行在本机，提供socks5服务给client端，用于加密用户的请求并转发到server端
具体协议的规范如下：[shadowsocks协议](https://shadowsocks.org/en/spec/Protocol.html) ， [socks5协议](https://tools.ietf.org/html/rfc1928)

**Comment by HuanMeng0** [comment]
了解了一下，也就是这个项目不和现在的shadowsocks兼容吗？

**Comment by VincentChanX** [comment]
@HuanMeng0 是的，不兼容原来的shadowsocks
