### ISSUE TITLE
按步骤做了，还是不能用，是被墙了

### ISSUE THREAD

**Issue by bingo8670** [VincentChanX/shadowsocks-over-websocket#13]
按步骤做了，还是不能用，是被墙了

**Comment by VincentChanX** [comment]
是可以用的，有可能你那边的网络连接heroku失败吧

2017-10-20 16:23 GMT+08:00 bingo8670 <notifications@github.com>:

**Comment by bingo8670** [comment]
谢谢楼主，已经解决了，是端口的问题
