### ISSUE TITLE
0

### ISSUE THREAD

**Issue by zx3777** [VincentChanX/shadowsocks-over-websocket#20]
如题

**Comment by caonimac** [comment]
可以布署v2ray heroku，然后用v2ray

**Comment by zx3777** [comment]
v2ray和这个比有什么缺点和优点呢

caonimac <notifications@github.com> 于2018年2月10日周六 下午3:14写道：

**Comment by lishen226** [comment]
@caonimac 您的一句话，让我打开了新世界的大门

**Comment by whtiehack** [comment]
v2ray heroku 被封了吧
